// app/(main)/learn/page.tsx
import { redirect } from "next/navigation";

import { 
  getCourseProgress, 
  getLessonPercentage, 
  getUnits, 
  getUserProgress,
} from "@/db/queries";
import { FeedWrapper } from "@/components/feed-wrapper";
import { UserProgress } from "@/components/user-progress";
import { StickyWrapper } from "@/components/sticky-wrapper";
// import { lessons, units as unitsSchema } from "@/db/schema";

// import { Unit } from "./unit";
import { Header } from "./header";

const LearnPage = async () => {
  // pull the user progress data
  const userProgressData = getUserProgress();
  const unitsData = getUnits();

  const [
    userProgress,
    units,
  ] = await Promise.all([
    userProgressData,
    unitsData,
  ]);

  // if userprogress or a course has not been set, redirect to courses
  if (!userProgress || !userProgress.activeCourse){
    redirect("/courses");
  }

    return (
        <div className="flex flex-row-reverse gap-[48px] px-6">
      <StickyWrapper>
        <UserProgress
          activeCourse={{id:1, title: "Skeletal System", imageSrc: "/bone.svg"}}
          hearts={5}
          points={100}
        />
      </StickyWrapper>
      <FeedWrapper>
        <Header title="Skeletal System" />
        {units.map((unit) => (
          <div key={unit.id} className="mb-10">
            {JSON.stringify(unit)}
          </div>
        ))}
      </FeedWrapper>
    </div>
    );
}

export default LearnPage;

// src/routes/(main)/learn/+page.svelte
<script>
    import FeedWrapper from "$lib/components/feed-wrapper.svelte";
    import UserProgress from "$lib/components/user-progress.svelte";
    import StickyWrapper from "$lib/components/sticky-wrapper.svelte";

    import {Button} from "$lib/components/ui/button";
    import {ArrowLeft} from "lucide-svelte"
</script>


<div class="flex flex-row-reverse gap-[48px] px-6">
    <StickyWrapper>
      <UserProgress
        activeCourse={{ title: "Skeletal", imageSrc: "/bone.svg" }}
        hearts={5}
        points={100}
        hasActiveSubscription={false}
      />
    </StickyWrapper>
    <FeedWrapper>
        <div class="sticky top-0 bg-white pb-3 lg:pt-[28px] lg:mt-[-28px] flex items-center justify-between border-b-2 mb-5 text-neutral-400 lg:z-50">
            <a href="/courses">
              <Button variant="ghost" size="sm">
                <ArrowLeft class="h-5 w-5 stroke-2 text-neutral-400" />
              </Button>
            </a>
            <h1 class="font-bold text-lg">
              Skeletal System
            </h1>
            <div />
          </div>
        </FeedWrapper>
  </div>
