// src/routes/(main)/courses/card.svelte
<script lang="ts">
	import { Check } from 'lucide-svelte';
	import { cn } from '$lib/utils';

	// implicitly define their types
	export let title: string;
	export let imageSrc: string;
	export let id: number;
	export let onClick: (id: number) => void;
	export let disabled: boolean;
	export let active: boolean;
</script>

<div
	on:click={() => onClick(id)}
	class={cn(
		'flex h-full min-h-[217px] min-w-[200px] cursor-pointer flex-col items-center justify-between rounded-xl border-2 border-b-4 p-3 pb-6 hover:bg-black/5 active:border-b-2',
		disabled && 'pointer-events-none opacity-50'
	)}
>
	<div class="min-[24px] flex w-full items-center justify-end">
		<!-- Don't render this unless it's their active course -->
		{#if active}
			<div class="flex items-center justify-center rounded-md bg-green-600 p-1.5">
				<Check class="h-4 w-4 stroke-[4] text-white" />
			</div>
		{/if}
	</div>
	<!-- Course image -->
	<img
		src={imageSrc}
		alt={title}
		height={70}
		width={93.33}
		class="rounded-lg border object-cover drop-shadow-md"
	/>
	<!-- Course name -->
	<p class="mt-3 text-center font-bold text-neutral-700">
		{title}
	</p>
</div>

// app/lesson/card.tsx
import Image from "next/image";

import { cn } from "@/lib/utils";
import { challenges } from "@/db/schema";

type Props = {
  id: number;
  imageSrc: string | null;
  audioSrc: string | null;
  text: string;
  shortcut: string;
  selected?: boolean;
  onClick: () => void;
  disabled?: boolean;
  status?: "correct" | "wrong" | "none",
  type: typeof challenges.$inferSelect["type"];
};

export const Card = ({
  id,
  imageSrc,
  audioSrc,
  text,
  shortcut,
  selected,
  onClick,
  status,
  disabled,
  type,
}: Props) => {

  return (
    <div
      onClick={() => {}}
      className={cn(
        "h-full border-2 rounded-xl border-b-4 hover:bg-black/5 p-4 lg:p-6 cursor-pointer active:border-b-2",
        selected && "border-sky-300 bg-sky-100 hover:bg-sky-100",
        selected && status === "correct" 
          && "border-green-300 bg-green-100 hover:bg-green-100",
        selected && status === "wrong" 
          && "border-rose-300 bg-rose-100 hover:bg-rose-100",
        disabled && "pointer-events-none hover:bg-white",
        type === "ASSIST" && "lg:p-3 w-full"
      )}
    >
      {imageSrc && (
        <div
          className="relative aspect-square mb-4 max-h-[80px] lg:max-h-[150px] w-full"
        >
          <Image src={imageSrc} fill alt={text} />
        </div>
      )}
      <div className={cn(
        "flex items-center justify-between",
        type === "ASSIST" && "flex-row-reverse",
      )}>
        {type === "ASSIST" && <div />}
        <p className={cn(
          "text-neutral-600 text-sm lg:text-base",
          selected && "text-sky-500",
          selected && status === "correct" 
            && "text-green-500",
          selected && status === "wrong" 
            && "text-rose-500",
        )}>
          {text}
        </p>
        <div className={cn(
          "lg:w-[30px] lg:h-[30px] w-[20px] h-[20px] border-2 flex items-center justify-center rounded-lg text-neutral-400 lg:text-[15px] text-xs font-semibold",
          selected && "border-sky-300 text-sky-500",
          selected && status === "correct" 
            && "border-green-500 text-green-500",
          selected && status === "wrong" 
            && "border-rose-500 text-rose-500",
        )}>
          {shortcut}
        </div>
      </div>
    </div>
  );
};
