// src/routes/(main)/courses/list.svelte
<script lang="ts">
	import { courses, userProgress } from '../../../db/schema';

	import Card from './card.svelte'; // Assuming you have a Card component

	// Define props for the List component
	export let coursesData: { id: number; title: string; imageSrc: string }[] = [];
	export let activeCourseId: number | null = null;
</script>

<div class="grid grid-cols-2 gap-4 pt-6 lg:grid-cols-[repeat(auto-fill,minmax(210px,1fr))]">
	<!-- Foreach course in coursesData -->
	{#each coursesData as course}
		<Card
			id={course.id}
			title={course.title}
			imageSrc={course.imageSrc}
			onClick={() => {}}
			active={course.id === activeCourseId}
			disabled={false}
		/>
	{/each}
</div>

// app/(main)/courses/list.tsx
"use client";

import { useTransition } from "react";
import { useRouter } from "next/navigation";

import { courses, userProgress } from "@/db/schema";
import { upsertUserProgress } from "@/actions/user-progress";

import { Card } from "./card";

type Props = {
  courses: typeof courses.$inferSelect[];
  // activeCourseId?: number;
  activeCourseId?: typeof userProgress.$inferSelect.activeCourseId;
};

export const List = ({ courses, activeCourseId }: Props) => {
  const router = useRouter();
  const [pending, startTransition] = useTransition();

  const onClick = (id: number) => {
    if (pending) return;

    // if the user has already clicked on a course they have active, do not update db
    if (id === activeCourseId) {
      // redirect user to /learn
      return router.push("/learn");
    }

    // if a user joins a new course
    startTransition(() => {
      upsertUserProgress(id);
    });
  };

  return (
    <div className="pt-6 grid grid-cols-2 lg:grid-cols-[repeat(auto-fill,minmax(210px,1fr))] gap-4">
      {courses.map((course) => (
        <Card
          key={course.id}
          id={course.id}
          title={course.title}
          imageSrc={course.imageSrc}
          onClick={onClick} // accepts the id
          disabled={pending}
          active={course.id === activeCourseId}
        />
      ))}
    </div>
  );
};
